version: '3'

services:

  prestashop:
    image: prestashop/prestashop
    container_name: prestashop    
    environment:
      DB_SERVER: mysqlprestas
    ports:
      - "8081:80"
    restart: always
    networks:
      - prestashop-net

  mysql:
    image: mysql:5.7
    container_name: mysqlprestas
    environment:
      MYSQL_ROOT_PASSWORD: admin
    restart: always
    ports:
      - "3007:3306"
    networks:
      - prestashop-net

networks:
  prestashop-net: